runtime: nodejs10
service: programs
entrypoint: node ./dist/main.js

env_variables:
  NODE_ENV: "production"
  GOOGLE_APPLICATION_CREDENTIALS: "./corepetro-57e280214c92.json"
  SECRET_TOKEN: "maladeira"